Added init mode - Added .fsync/remote and .fsync/ignore as config files - Added -d/--debug flag for verbose output

diff --git a/filesync b/filesync
--- a/filesync
+++ b/filesync
@@ -1,56 +1,115 @@
 #!/bin/bash
 
 declare -r sync_comm="rsync -az --update"
+declare -r metadir='.fsync'
 
-while [[ $# -ne 0 ]]; do
-	case "$1" in
-		-h|--help)
-			printf "Usage: filesync [options]\n"
-			printf "\n"
-			printf "Options:\n"
-			printf "  %-28s %s\n" "-h, --help" "display this text"
-			printf "\n"
-			exit 0
-			;;
-	esac
-	shift
-done
+_do_init() {
+	if [[ -d "$metadir" ]]; then
+		echo "Fatal: filesync directory already initialized as '$(pwd)/$metadir'" >&2
+		exit 1
+	fi
+	if [[ -z "$init_remote" ]]; then
+		echo "Fatal: must specify remote (ex: filesync init <remote>)" >&2
+		exit 2
+	fi
+	mkdir "$metadir"
+	echo "$init_remote" > "$metadir/remote"
+	echo "Filesync directory initialized."
+}
 
-target=$(pwd)
-if [[ ! -f "$target/.fsync" ]]; then
-	echo "Fatal: not a filesync directory; .fsync not found." >&2
-	exit 1
-fi
+_do_sync() {
+	target=$(pwd)
+	if [[ ! -d "$target/$metadir" ]]; then
+		echo "Fatal: not a filesync directory; $metadir/ not found." >&2
+		exit 1
+	fi
 
-remote_path="$(< "$target/.fsync")"
-remote_path="${remote_path%/}"
-if [[ -z "$remote_path" ]]; then
-	echo "Fatal: no remote path specified in $target/.fsync" >&2
-	exit 1
-fi
+	remote_path="$(< "$target/$metadir/remote")"
+	remote_path="${remote_path%/}"
+	if [[ -z "$remote_path" ]]; then
+		echo "Fatal: no remote path specified in $target/$metadir/remote" >&2
+		exit 1
+	fi
 
-echo "Syncing $(pwd)..."
+	echo "Syncing $(pwd)..."
 
-if echo "$remote_path" | grep ':' >/dev/null; then
-	remote_host="${remote_path%%:*}"
-	remote_host_path="${remote_path#*:}"
-	ssh "$remote_host" "mkdir -p $remote_host_path"
-fi
+	exclude=""
+	if [[ -f "$target/$metadir/ignore" ]]; then
+		while read line; do
+			exclude="$exclude--exclude=$line "
+		done<"$target/$metadir/ignore"
+		"$verbose" && echo "[Debug] Built exclude line"
+	fi
+
+	if echo "$remote_path" | grep ':' >/dev/null; then
+		remote_host="${remote_path%%:*}"
+		remote_host_path="${remote_path#*:}"
+		ssh "$remote_host" "mkdir -p $remote_host_path"
+		"$verbose" && echo "[Debug] Created remote path"
+	fi
+
+	if _run_sync; then
+		echo "Sync successful"
+	else
+		echo "Sync failed" >&2
+		exit 1
+	fi
+}
 
 _run_sync() {
-	if ! $sync_comm "$remote_path/" "$target"; then
+	"$verbose" && echo "[Debug] Running pull..."
+	"$verbose" && echo "[Debug] -> $sync_comm $exclude \"$remote_path/\" \"$target\""
+	if ! $sync_comm $exclude "$remote_path/" "$target"; then
 		echo "Error: failed to pull changes" >&2
 		return 1
 	fi
-	if ! $sync_comm "$target/" "$remote_path"; then
+
+	"$verbose" && echo "[Debug] Running push..."
+	"$verbose" && echo "[Debug] -> $sync_comm $exclude \"$target/\" \"$remote_path\""
+	if ! $sync_comm $exclude "$target/" "$remote_path"; then
 		echo "Error: fail to push changes" >&2
 		return 1
 	fi
 }
 
-if _run_sync; then
-	echo "Sync successful"
-else
-	echo "Sync failed" >&2
-	exit 1
-fi
+declare mode="sync"
+declare init_remote
+declare verbose=false
+
+while [[ $# -ne 0 ]]; do
+	case "$mode" in
+		sync)
+			case "$1" in
+				-d|--debug)
+					verbose=true
+					;;
+				-h|--help)
+					printf "Usage: filesync [options] [mode]\n"
+					printf "\n"
+					printf "  %-8s %s\n" "init" "initialize a new filesync directory"
+					printf "\n"
+					printf "Options:\n"
+					printf "  %-28s %s\n" "-d, --debug" "enable verbose debug messages"
+					printf "  %-28s %s\n" "-h, --help" "display this text"
+					exit 0
+					;;
+				init)
+					mode="init"
+					;;
+			esac
+			;;
+		init)
+			case "$1" in
+				*)
+					init_remote="${init_remote:=$1}"
+					;;
+			esac
+			;;
+	esac
+	shift
+done
+
+case "$mode" in
+	init) _do_init ;;
+	sync) _do_sync ;;
+esac
